apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-react-ingress
  namespace: frontend-prod
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing" 
    alb.ingress.kubernetes.io/target-type: "ip"
    # alb.ingress.kubernetes.io/cert-arn
  
spec:
  rules:
    - host: furniture.awsmpc.asia 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-react-service 
                port:
                  number: 80