apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-react-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: frontend-react
spec:
  project: frontend-furniture 
  source:
    repoURL: 'https://github.com/pengchao2022/gallery-frontend-react-cd.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true